version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.9.0  # Updated to Node 20.9.0

    working_directory: ~/gatsby-theme-chrisvogt

    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-store-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-store-

      - run:
          name: Install pnpm
          command: |
            npm install -g pnpm

      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-store-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

      - run:
          name: Unit Tests w/Coverage
          command: pnpm workspace gatsby-theme-chrisvogt run test:coverage --maxWorkers=2

      - store_artifacts:
          path: theme/coverage

      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
