version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22 # Updated to Node 22

    working_directory: ~/gatsby-theme-chrisvogt

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run Prettier Check
          command: yarn prettier --check .

      - run:
          name: Run ESLint Check
          command: yarn lint

      - run:
          name: Unit Tests w/Coverage
          command: yarn workspace gatsby-theme-chrisvogt test:coverage --maxWorkers=2

      - store_artifacts:
          path: theme/coverage

      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
