# CircleCI Firebase Deployment Config
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/gatsby-theme-private-sphere

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Tests w/Coverage
          command: yarn workspace gatsby-theme-private-sphere test:coverage

      - store_artifacts:
          path: theme/coverage

      - codecov/upload:
          file: theme/coverage/lcov.info
