/** @jsx jsx */
import { jsx } from 'theme-ui'
import { faRobot } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { Heading } from '@theme-ui/components'
import { Themed } from '@theme-ui/mdx'
import React from 'react'

import { parseSafeHtml } from '../../../helpers/safeHtmlParser'

const AiSummary = React.memo(({ aiSummary }) => {
  if (!aiSummary) {
    return null
  }

  return (
    <div sx={{ variant: 'cards.aiSummary', mb: 4 }}>
      <div sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
        <FontAwesomeIcon
          icon={faRobot}
          sx={{
            color: 'primary',
            fontSize: [2, 3],
            mr: 2,
            animation: 'pulse 2s infinite'
          }}
        />
        <Heading as='h3' sx={{ fontSize: [3, 4], mb: 0 }}>
          AI Summary
        </Heading>
      </div>

      <div sx={{ mb: 3 }}>{parseSafeHtml(aiSummary)}</div>

      <Themed.p
        sx={{
          mb: 0,
          fontSize: [1, 2],
          color: 'textMuted',
          fontStyle: 'italic',
          display: 'flex',
          alignItems: 'center'
        }}
      >
        <FontAwesomeIcon
          icon={faRobot}
          sx={{
            fontSize: 1,
            mr: 1,
            opacity: 0.7
          }}
        />
        Generated by Gemini (AI)
      </Themed.p>
    </div>
  )
})

export default AiSummary
